name: HTML Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check HTML5
      uses: Cyb3r-Jak3/html5validator-action
      with:
        root: ./
        action_debug: true